FROM kalilinux/kali-rolling:latest

RUN apt-get update && apt-get upgrade -y

RUN apt-get install -y \
    metasploit-framework \
    nmap \
    net-tools \
    iputils-ping \
    python3 \
    python3-pip \
    iproute2 \
