version: '3'
services:
  wazuh:
    image: wazuh/wazuh:4.2.7
    hostname: wazuh
    networks:
      lab_net:
        ipv4_address: 172.40.0.2
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
      - "55000:55000/udp"

  wazuh-kibana:
    image: wazuh/wazuh-kibana:4.2.7
    networks:  
      lab_net:
        ipv4_address: 172.40.0.3
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    networks:
      lab_net:
        ipv4_address: 172.40.0.4
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"

  suricata:
    image: jasonish/suricata:latest
    networks:
      lab_net:
        ipv4_address: 172.40.0.5
    command: ["-i", "eth0"]
    volumes:
      - ./suricata:/etc/suricata
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - "3000:3000"

  attack:
    image: test/kali_attack
    networks:
      lab_net:
        ipv4_address: 172.40.0.201
    cap_add:
      - NET_ADMIN
      - NET_RAW
    privileged: true
    stdin_open: true
    command: /bin/sh

  gateway:
    image: test/lab_gateway
    container_name: gateway
    networks:
      lab_net:
        ipv4_address: 172.40.0.200
    privileged: true
    command: sh -c "sleep infinity"
    cap_add:
      - NET_ADMIN
      - NET_RAW

networks:
  lab_net:
    external: true
